//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeEntryInfo
    {
        public int FeeEntryId { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable< int> TotalStudent { get; set; }
        public Nullable<decimal> FeeperStudent { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public string TranjectionId { get; set; }
        public Nullable<int> ApprovedId { get; set; }
        public Nullable<int> GrantedMemberId { get; set; }
        public string PayDate { get; set; }
    }
}
