//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Company_InformationEntities : DbContext
    {
        public Company_InformationEntities()
            : base("name=Company_InformationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovedInfo> ApprovedInfoes { get; set; }
        public virtual DbSet<BranchInfo> BranchInfoes { get; set; }
        public virtual DbSet<ClassInfo> ClassInfoes { get; set; }
        public virtual DbSet<DistrictInfo> DistrictInfoes { get; set; }
        public virtual DbSet<DivisionInfo> DivisionInfoes { get; set; }
        public virtual DbSet<EStatusInfo> EStatusInfoes { get; set; }
        public virtual DbSet<FeeEntryInfo> FeeEntryInfoes { get; set; }
        public virtual DbSet<GenderInfo> GenderInfoes { get; set; }
        public virtual DbSet<InstituteInfo> InstituteInfoes { get; set; }
        public virtual DbSet<InsTypeInfo> InsTypeInfoes { get; set; }
        public virtual DbSet<MonthInfo> MonthInfoes { get; set; }
        public virtual DbSet<PaymentmethodInfo> PaymentmethodInfoes { get; set; }
        public virtual DbSet<PaymentStatusInfo> PaymentStatusInfoes { get; set; }
        public virtual DbSet<PStatusInfo> PStatusInfoes { get; set; }
        public virtual DbSet<StatusInfo> StatusInfoes { get; set; }
        public virtual DbSet<TraneeInfo> TraneeInfoes { get; set; }
        public virtual DbSet<TTypeInfo> TTypeInfoes { get; set; }
        public virtual DbSet<UpazilaInfo> UpazilaInfoes { get; set; }
        public virtual DbSet<Yearinfo> Yearinfoes { get; set; }
    }
}
