//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraneeInfo
    {
        public int TraneeId { get; set; }
        public string TraneeName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> Upazilaid { get; set; }
        public Nullable<int> division_id { get; set; }
        public Nullable<int> TraneeTypeId { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public string JoiningDate { get; set; }
        public string NID { get; set; }
        public string DOB { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> EStatusId { get; set; }
        public Nullable<int> PStatusId { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public string BloodGroup { get; set; }
        public string UName { get; set; }
        public string Password { get; set; }
    }
}
