//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpazilaInfo
    {
        public int Upazilaid { get; set; }
        public int DistrictId { get; set; }
        public string name { get; set; }
        public string bn_name { get; set; }
        public string url { get; set; }
    }
}
