/// <reference path="jquery-ui-1.12.1.js" />
/// <autosync enabled="true" />
/// <reference path="respond.js" />
/// <reference path="../bootstrap 5/bootstrap-4.5.3-dist/js/bootstrap.bundle.js" />
/// <reference path="../bootstrap 5/bootstrap-4.5.3-dist/js/bootstrap.js" />
/// <reference path="../content/popper.min.js" />
/// <reference path="ai.0.22.9-build00167.min.js" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-1.12.4.min.js" />
/// <reference path="jquery-ui-1.12.1.min.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
